fixed scripts

diff --git a/bin/index b/bin/index
--- a/bin/index
+++ b/bin/index
@@ -15,12 +15,34 @@ fi
 # Parse argument.  $1 is the first argument
 case $1 in
   "start")
-    echo "starting index server ..."
-    mkdir -p var/log
-    rm -f var/log/index.log
-    FLASK_APP=index INDEX_PATH="inverted_index_0.txt" flask run --host 0.0.0.0 --port 9000 >> var/log/index.log 2>&1 &
-    FLASK_APP=index INDEX_PATH="inverted_index_1.txt" flask run --host 0.0.0.0 --port 9001 >> var/log/index.log 2>&1 &
-    FLASK_APP=index INDEX_PATH="inverted_index_2.txt" flask run --host 0.0.0.0 --port 9002 >> var/log/index.log 2>&1 &
+  set +o pipefail
+    NPROCS=$(pgrep -f "flask run --host 0.0.0.0 --port 900[0-2]" | wc -l)
+    set -o pipefail
+    if [ "$NPROCS" -eq 3 ]; then
+      echo"Error: index server is already running"
+      exit 1
+    elif [ "$NPROCS" -eq 2 ]; then
+      echo "starting index server ..."
+      mkdir -p var/log
+      rm -f var/log/index.log
+      FLASK_APP=index INDEX_PATH="inverted_index_0.txt" flask run --host 0.0.0.0 --port 9000 >> var/log/index.log 2>&1 &
+      FLASK_APP=index INDEX_PATH="inverted_index_1.txt" flask run --host 0.0.0.0 --port 9001 >> var/log/index.log 2>&1 &
+      FLASK_APP=index INDEX_PATH="inverted_index_2.txt" flask run --host 0.0.0.0 --port 9002 >> var/log/index.log 2>&1 &
+    elif [ "$NPROCS" -eq 1 ]; then
+      echo "starting index server ..."
+      mkdir -p var/log
+      rm -f var/log/index.log
+      FLASK_APP=index INDEX_PATH="inverted_index_0.txt" flask run --host 0.0.0.0 --port 9000 >> var/log/index.log 2>&1 &
+      FLASK_APP=index INDEX_PATH="inverted_index_1.txt" flask run --host 0.0.0.0 --port 9001 >> var/log/index.log 2>&1 &
+      FLASK_APP=index INDEX_PATH="inverted_index_2.txt" flask run --host 0.0.0.0 --port 9002 >> var/log/index.log 2>&1 &
+    elif [ "$NPROCS" -eq 0 ]; then
+      echo "starting index server ..."
+      mkdir -p var/log
+      rm -f var/log/index.log
+      FLASK_APP=index INDEX_PATH="inverted_index_0.txt" flask run --host 0.0.0.0 --port 9000 >> var/log/index.log 2>&1 &
+      FLASK_APP=index INDEX_PATH="inverted_index_1.txt" flask run --host 0.0.0.0 --port 9001 >> var/log/index.log 2>&1 &
+      FLASK_APP=index INDEX_PATH="inverted_index_2.txt" flask run --host 0.0.0.0 --port 9002 >> var/log/index.log 2>&1 &
+    fi
     ;;
   "stop")
     echo "stopping index server ..."
diff --git a/bin/search b/bin/search
--- a/bin/search
+++ b/bin/search
@@ -13,24 +13,26 @@ fi
 # Parse argument.  $1 is the first argument
 case $1 in
   "start")
-    # if db does not exist
-    if [ ! -f var/index.sqlite3 ];
-    then
-        echo "can't find search database var/index.sqlite3"
+    ./bin/index status
+    OUTPUT=$?
+    if OUTPUT == "index server stopped"; then
+        echo "Error: index server is  not running"
         exit 1
-    # if index server is not running
-    elif ./bin/index status | grep -q 'index server stopped'; then
-        echo "Error: index server is not running"
-        exit 1
+    fi
     # if search server is already running
-    elif pgrep -f "flask run --host 0.0.0.0 --port 8000"; then
+    if pgrep -f "flask run --host 0.0.0.0 --port 8000"; then
         echo "Error: search server is already running"
         exit 1
-    else
+    fi
+    if [ -f var/index.sqlite3 ];
+    then
         echo "starting search server ..."
         mkdir -p var/log
         rm -f var/log/search.log
-        FLASK_APP=search flask run --host 0.0.0.0 --port 8000 &> var/log/search.log &
+        FLASK_APP=search flask run --host 0.0.0.0 --port 8000 &> var/log/search.log &\
+    else
+        echo "can't find search database var/index.sqlite3"
+        exit 1
     fi
     ;;
   "stop")
